/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TulemusRouteImport } from './routes/tulemus'
import { Route as PrivaatsusRouteImport } from './routes/privaatsus'
import { Route as KuidasSeeToimibRouteImport } from './routes/kuidas-see-toimib'
import { Route as KaardistaRouteImport } from './routes/kaardista'
import { Route as AbiRouteImport } from './routes/abi'
import { Route as IndexRouteImport } from './routes/index'

const TulemusRoute = TulemusRouteImport.update({
  id: '/tulemus',
  path: '/tulemus',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivaatsusRoute = PrivaatsusRouteImport.update({
  id: '/privaatsus',
  path: '/privaatsus',
  getParentRoute: () => rootRouteImport,
} as any)
const KuidasSeeToimibRoute = KuidasSeeToimibRouteImport.update({
  id: '/kuidas-see-toimib',
  path: '/kuidas-see-toimib',
  getParentRoute: () => rootRouteImport,
} as any)
const KaardistaRoute = KaardistaRouteImport.update({
  id: '/kaardista',
  path: '/kaardista',
  getParentRoute: () => rootRouteImport,
} as any)
const AbiRoute = AbiRouteImport.update({
  id: '/abi',
  path: '/abi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abi': typeof AbiRoute
  '/kaardista': typeof KaardistaRoute
  '/kuidas-see-toimib': typeof KuidasSeeToimibRoute
  '/privaatsus': typeof PrivaatsusRoute
  '/tulemus': typeof TulemusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abi': typeof AbiRoute
  '/kaardista': typeof KaardistaRoute
  '/kuidas-see-toimib': typeof KuidasSeeToimibRoute
  '/privaatsus': typeof PrivaatsusRoute
  '/tulemus': typeof TulemusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abi': typeof AbiRoute
  '/kaardista': typeof KaardistaRoute
  '/kuidas-see-toimib': typeof KuidasSeeToimibRoute
  '/privaatsus': typeof PrivaatsusRoute
  '/tulemus': typeof TulemusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abi'
    | '/kaardista'
    | '/kuidas-see-toimib'
    | '/privaatsus'
    | '/tulemus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abi'
    | '/kaardista'
    | '/kuidas-see-toimib'
    | '/privaatsus'
    | '/tulemus'
  id:
    | '__root__'
    | '/'
    | '/abi'
    | '/kaardista'
    | '/kuidas-see-toimib'
    | '/privaatsus'
    | '/tulemus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbiRoute: typeof AbiRoute
  KaardistaRoute: typeof KaardistaRoute
  KuidasSeeToimibRoute: typeof KuidasSeeToimibRoute
  PrivaatsusRoute: typeof PrivaatsusRoute
  TulemusRoute: typeof TulemusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tulemus': {
      id: '/tulemus'
      path: '/tulemus'
      fullPath: '/tulemus'
      preLoaderRoute: typeof TulemusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privaatsus': {
      id: '/privaatsus'
      path: '/privaatsus'
      fullPath: '/privaatsus'
      preLoaderRoute: typeof PrivaatsusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuidas-see-toimib': {
      id: '/kuidas-see-toimib'
      path: '/kuidas-see-toimib'
      fullPath: '/kuidas-see-toimib'
      preLoaderRoute: typeof KuidasSeeToimibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaardista': {
      id: '/kaardista'
      path: '/kaardista'
      fullPath: '/kaardista'
      preLoaderRoute: typeof KaardistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abi': {
      id: '/abi'
      path: '/abi'
      fullPath: '/abi'
      preLoaderRoute: typeof AbiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbiRoute: AbiRoute,
  KaardistaRoute: KaardistaRoute,
  KuidasSeeToimibRoute: KuidasSeeToimibRoute,
  PrivaatsusRoute: PrivaatsusRoute,
  TulemusRoute: TulemusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
